apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: pod-creator-binding
    namespace: default
subjects:
    - kind: ServiceAccount
      name: default  # Specify the service account name here
      namespace: default
roleRef:
    kind: Role
    name: pod-creator
    apiGroup: rbac.authorization.k8s.io
