kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-creator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "update", "delete", "list","watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "update", "delete", "list", "watch"]
